apiVersion: v1
kind: Service

metadata:
  name: lb-test
  namespace: lb-test
  labels:
    chlorinate.rokoucha.com/lb: public
    external-dns.rokoucha.com/scope: lb-test
  annotations:
    lbipam.cilium.io/sharing-key: public-dmz
    external-dns.alpha.kubernetes.io/controller: lb-test
    lb-test.external-dns.alpha.kubernetes.io/hostname: lb-test.ggrel.net

spec:
  selector:
    app: lb-test
  type: LoadBalancer
  ipFamilyPolicy: RequireDualStack
  ipFamilies:
    - IPv4
    - IPv6
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 80
      targetPort: 80
