apiVersion: v1
kind: PersistentVolume

metadata:
  name: pvc-13bfda61-2e00-4784-b7f3-611b94d01499

spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data
    namespace: prometheus
  csi:
    driver: csi.san.synology.com
    fsType: btrfs
    volumeAttributes:
      baseDir: ""
      dsm: 172.16.2.17
      formatOptions: --nodiscard
      mountPermissions: ""
      protocol: iscsi
      source: ""
      storage.kubernetes.io/csiProvisionerIdentity: 1740323674035-8081-csi.san.synology.com
    volumeHandle: 08cb563d-4923-4be2-9545-11fde8bd1179
  persistentVolumeReclaimPolicy: Delete
  storageClassName: beryllium-iscsi
  volumeMode: Filesystem
