apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector

metadata:
  name: otelcol-gateway

spec:
  config:
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
      prometheus:
        config:
          scrape_configs:
            - job_name: otel-collector
              scrape_interval: 10s
              static_configs:
                - targets: ["0.0.0.0:8888"]

    processors:
      memory_limiter:
        check_interval: 1s
        limit_mib: 2000
        spike_limit_mib: 500
      resource:
        attributes:
          - key: service.namespace
            value: materia
            action: upsert

    exporters:
      mackerelotlp: {}
      otlphttp/prometheus:
        metrics_endpoint: http://prometheus-operated.prometheus.svc.materia-cluster.ggrel.net:9090/api/v1/otlp/v1/metrics

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, resource]
          exporters: [mackerelotlp]
        metrics:
          receivers: [otlp, prometheus]
          processors: [memory_limiter, resource]
          exporters: [mackerelotlp, otlphttp/prometheus]
  envFrom:
    - secretRef:
        name: mackerel-apikey
  image: ghcr.io/rokoucha/otelcol/materia-gateway:sha-bad26a8
  mode: statefulset
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: RequireDualStack
