apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector

metadata:
  name: otelcol-legacy

spec:
  config:
    receivers:
      prometheus/self:
        config:
          scrape_configs:
            - job_name: opentelemetry-collector
              scrape_interval: 10s
              static_configs:
                - targets: ["0.0.0.0:8888"]
      prometheus:
        config:
          global:
            scrape_interval: 15s
          scrape_configs:
            - job_name: apcupsd-exporter
              static_configs:
                - targets:
                    - service.apcupsd-exporter.svc.materia-cluster.ggrel.net:9162
            - job_name: blackbox/ping_bbix-4over6-v4
              scrape_interval: 1m
              metrics_path: /probe
              params:
                module: [ping_bbix-4over6-v4]
              static_configs:
                - targets:
                    - 172.16.10.1
                    - 1.1.1.1
                    - 8.8.8.8
                    - ping-e.sinet.ad.jp
              relabel_configs:
                - source_labels: [__address__]
                  target_label: __param_target
                - source_labels: [__param_target]
                  target_label: instance
                - target_label: __address__
                  replacement: nitrogen.dns.ggrel.net:9115
                - target_label: network
                  replacement: bbix-4over6-v4
            - job_name: blackbox/ping_bbix-pppoe-v4
              scrape_interval: 1m
              metrics_path: /probe
              params:
                module: [ping_bbix-pppoe-v4]
              static_configs:
                - targets:
                    - 172.16.10.1
                    - 1.1.1.1
                    - 8.8.8.8
                    - ping-e.sinet.ad.jp
              relabel_configs:
                - source_labels: [__address__]
                  target_label: __param_target
                - source_labels: [__param_target]
                  target_label: instance
                - target_label: __address__
                  replacement: nitrogen.dns.ggrel.net:9115
                - source_labels: [__param_module]
                  target_label: module
                - target_label: network
                  replacement: bbix-pppoe-v4
            - job_name: blackbox/ping_mobile-v4
              scrape_interval: 1m
              metrics_path: /probe
              params:
                module: [ping_mobile-v4]
              static_configs:
                - targets:
                    - 172.16.10.1
                    - 1.1.1.1
                    - 8.8.8.8
                    - ping-e.sinet.ad.jp
              relabel_configs:
                - source_labels: [__address__]
                  target_label: __param_target
                - source_labels: [__param_target]
                  target_label: instance
                - target_label: __address__
                  replacement: nitrogen.dns.ggrel.net:9115
                - source_labels: [__param_module]
                  target_label: module
                - target_label: network
                  replacement: mobile-v4
            - job_name: blackbox/ping_itscom-v4
              scrape_interval: 1m
              metrics_path: /probe
              params:
                module: [ping_itscom-v4]
              static_configs:
                - targets:
                    - 172.16.10.1
                    - 1.1.1.1
                    - 8.8.8.8
                    - ping-e.sinet.ad.jp
              relabel_configs:
                - source_labels: [__address__]
                  target_label: __param_target
                - source_labels: [__param_target]
                  target_label: instance
                - target_label: __address__
                  replacement: nitrogen.dns.ggrel.net:9115
                - source_labels: [__param_module]
                  target_label: module
                - target_label: network
                  replacement: itscom-v4
            - job_name: blackbox_exporter
              static_configs:
                - targets:
                    - nitrogen.dns.ggrel.net:9115
            - job_name: intel-igpu
              static_configs:
                - targets:
                    - haruka.dns.ggrel.net:8080
            - job_name: litestream
              static_configs:
                - targets:
                    - lithium.dns.ggrel.net:9090
            - job_name: snmp
              static_configs:
                - targets:
                    - "172.16.2.1"
              metrics_path: /snmp
              params:
                auth: [public_v2]
                module: [if_mib, nec_ix]
              relabel_configs:
                - source_labels: [__address__]
                  target_label: __param_target
                - source_labels: [__param_target]
                  target_label: instance
                - target_label: __address__
                  replacement: service.snmp-exporter.svc.materia-cluster.ggrel.net:9116
            - job_name: snmp_exporter
              static_configs:
                - targets:
                    - service.snmp-exporter.svc.materia-cluster.ggrel.net:9116
            - job_name: switchbot-meter
              scrape_interval: 2m
              metrics_path: /probe
              static_configs:
                - targets:
                    - CED37C9CA281
                    - D4DF46B693B1
                    - ED867D5919E9
              relabel_configs:
                - source_labels: [__address__]
                  target_label: __param_target
                - source_labels: [__param_target]
                  target_label: instance
                - target_label: __address__
                  replacement: service.switchbot-meter-exporter.svc.materia-cluster.ggrel.net:8888

    processors:
      batch: {}
      memory_limiter:
        check_interval: 1s
        limit_mib: 1024
        spike_limit_mib: 256
      resource/append_otelcol_agent_pod_ip:
        attributes:
          - key: k8s.pod.ip
            action: insert
            value: ${env:MY_POD_IP}

    exporters:
      otlp:
        endpoint: otelcol-gateway-collector-headless.monitoring.svc.materia-cluster.ggrel.net:4317
        tls:
          insecure: true

    connectors:
      routing/metrics:
        table:
          - condition: "true"
            pipelines:
              - metrics

    service:
      pipelines:
        metrics/self:
          receivers:
            - prometheus/self
          processors:
            - resource/append_otelcol_agent_pod_ip
          exporters:
            - routing/metrics
        metrics:
          receivers:
            - routing/metrics
            - prometheus
          processors:
            - memory_limiter
            - batch
          exporters:
            - otlp
  env:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.142.0
  mode: statefulset
  replicas: 1
