apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: apcupsd-exporter

spec:
  selector:
    matchLabels:
      app: apcupsd-exporter
  endpoints:
    - port: telemetry
      relabelings:
        - targetLabel: job
          replacement: apcupsd-exporter
