apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./resources/materia-public-ipv4.yaml
  - ./resources/materia-public-ipv6.yaml
  - ./resources/bgp-cluster-config.yaml
  - ./resources/bgp-peer-config.yaml
  - ./resources/bgp-advertisement.yaml

helmCharts:
  - name: cilium
    releaseName: cilium
    namespace: kube-system
    version: 1.19.4
    repo: https://helm.cilium.io
    includeCRDs: true
    valuesFile: ./values.yaml
