apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflare-ddns

resources:
  - ./resources/cloudflare-ddns-apitoken.yaml
  - ./resources/cloudflare-ddns-external.yaml
  - ./resources/cloudflare-ddns.yaml
  - ./resources/namespace.yaml

patches:
  - path: ./resources/namespace-pod-security-labels.yaml
    target:
      kind: Namespace
      name: cloudflare-ddns
