deploymentMode: SingleBinary

global:
  clusterDomain: materia-cluster.ggrel.net

loki:
  commonConfig:
    path_prefix: /var/loki
    replication_factor: 1

  # ストレージ設定 (ファイルシステムを使用)
  storage:
    type: filesystem

  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  # セキュリティコンテキストの設定 (Prometheusに合わせる)
  podSecurityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsUser: 1000
  containerSecurityContext:
    runAsUser: 1000
    runAsGroup: 2000
    runAsNonRoot: true

# 永続ストレージ (PVC) の設定
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    storageClass: beryllium-nfs
    size: 10Gi
  podSecurityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsUser: 1000

# SSDモード用のコンポーネントを 0 にしてバリデーションを回避
write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0
