apiVersion: v1
kind: Service

metadata:
  name: service

spec:
  selector:
    app: mahiron
  type: ClusterIP
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: RequireDualStack
  ports:
    - name: mahiron
      port: 40772
      targetPort: mahiron
