apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: haproxy-controller

resources:
  - ./resources/ggrel-net-certificate.yaml
  - ./resources/ingress-class.yaml
  - ./resources/materia-ggrel-net-certificate.yaml
  - ./resources/noa-pp-ua-certificate.yaml
  - ./resources/rokoucha-net-certificate.yaml
  - ./resources/sayn-wittgenste-in-certificate.yaml
  - https://raw.githubusercontent.com/haproxytech/kubernetes-ingress/v3.1.12/deploy/haproxy-ingress.yaml

patches:
  - path: ./patches/deployment.yaml
  - path: ./patches/haproxy-ingress-cm.yaml
  - path: ./patches/service.yaml

images:
  - name: haproxytech/kubernetes-ingress
    newTag: 3.1.12
