apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mirakurun

resources:
  - ./resources/config.yaml
  - ./resources/authentik-proxy-service.yaml
  - ./resources/statefulset.yaml
  - ./resources/ghcr-credentials.yaml
  - ./resources/ingress.yaml
  - ./resources/namespace.yaml
  - ./resources/persistent-volume-claim.yaml
  - ./resources/service.yaml
  - ./resources/tls.yaml
