apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: materia-cluster
spec:
  hosts:
    - role: controller
      ssh:
        address: boron.dns.ggrel.net
        user: core
        port: 22
    - role: worker
      ssh:
        address: carbon.dns.ggrel.net
        user: core
        port: 22
  k0s:
    version: v1.31.2+k0s.0
    versionChannel: stable
    dynamicConfig: false
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: materia-cluster
      spec:
        api:
          address: materia-cluster.ggrel.net
          k0sApiPort: 9443
          port: 6443
          sans:
            - materia-cluster.ggrel.net
            - boron.dns.ggrel.net
          extraArgs:
            service-node-port-range: 80-32767
        network:
          clusterDomain: materia-cluster.ggrel.net
          dualStack:
            enabled: true
            IPv6podCIDR: "fd00::/108"
            IPv6serviceCIDR: "fd01::/108"
          kubeProxy:
            disabled: true
          podCIDR: 10.244.0.0/16
          provider: custom
          serviceCIDR: 10.96.0.0/12
        storage:
          type: kine
          kine:
            dataSource: "sqlite:///var/lib/k0s/db/state.db?more=rwc&_journal=WAL&cache=shared"
        telemetry:
