clusterName: materia-cluster
talosVersion: v1.12.6
kubernetesVersion: v1.36.0

endpoint: https://materia-cluster.ggrel.net:6443

allowSchedulingOnControlPlanes: true

domain: materia-cluster.ggrel.net

additionalApiServerCertSans:
  - materia-cluster.ggrel.net
  - 172.16.2.20

additionalMachineCertSans:
  - materia-cluster.ggrel.net
  - 172.16.2.20
  - hydrogen.dns.ggrel.net
  - lithium.dns.ggrel.net
  - phosphorus.dns.ggrel.net

clusterPodNets:
  - 10.244.0.0/16
  - fd00::/108
clusterSvcNets:
  - 10.96.0.0/12
  - fd01::/108

cniConfig:
  name: none

controlPlane:
  patches:
    - |-
      cluster:
        proxy:
          disabled: true
        apiServer:
          extraArgs:
            service-node-port-range: "80-32767"
        controllerManager:
          extraArgs:
            allocate-node-cidrs: "false"
      machine:
        install:
          image: factory.talos.dev/metal-installer-secureboot/6c4436014f0b7e48a5aafb5840d160d5943fe937011c56d0307a95d49f7517a2:v1.13.0
        systemDiskEncryption:
          state:
            provider: luks2
            keys:
              - slot: 0
                tpm: {}
          ephemeral:
            provider: luks2
            keys:
              - slot: 0
                tpm: {}

nodes:
  - hostname: hydrogen
    ipAddress: 172.16.2.21
    controlPlane: true
    installDiskSelector:
      type: nvme
    networkInterfaces:
      - deviceSelector:
          physical: true
        addresses:
          - 172.16.2.21/24
        routes:
          - network: 0.0.0.0/0
            gateway: 172.16.2.1
        dhcp: false
        vip:
          ip: 172.16.2.20

  - hostname: lithium
    ipAddress: 172.16.2.22
    controlPlane: true
    installDiskSelector:
      type: nvme
    networkInterfaces:
      - deviceSelector:
          physical: true
        addresses:
          - 172.16.2.22/24
        routes:
          - network: 0.0.0.0/0
            gateway: 172.16.2.1
        dhcp: false
        vip:
          ip: 172.16.2.20

  - hostname: phosphorus
    ipAddress: 172.16.2.23
    controlPlane: true
    installDiskSelector:
      type: nvme
    networkInterfaces:
      - deviceSelector:
          physical: true
        addresses:
          - 172.16.2.23/24
        routes:
          - network: 0.0.0.0/0
            gateway: 172.16.2.1
        dhcp: false
        vip:
          ip: 172.16.2.20
