global:
  env:
    - name: AUTHENTIK_POSTGRESQL__HOST
      valueFrom:
        secretKeyRef:
          name: postgresql-app
          key: host
    - name: AUTHENTIK_POSTGRESQL__USER
      valueFrom:
        secretKeyRef:
          name: postgresql-app
          key: user
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgresql-app
          key: password
    - name: AUTHENTIK_POSTGRESQL__NAME
      valueFrom:
        secretKeyRef:
          name: postgresql-app
          key: dbname

authentik:
  existingSecret:
    secretName: authentik

server:
  resources:
    requests:
      cpu: 200m
      memory: 768Mi
    limits:
      memory: 1Gi
  ingress:
    enabled: true
    ingressClassName: haproxy
    hosts:
      - auth.ggrel.net
    tls:
      - secretName: ggrel-net-tls
        hosts:
          - auth.ggrel.net

worker:
  resources:
    requests:
      cpu: 150m
      memory: 384Mi
    limits:
      memory: 640Mi
