apiVersion: v1
kind: Secret

metadata:
  name: ghcr-credentials
  annotations:
    reflector.v1.k8s.emberstack.com/reflected-at: ""
    reflector.v1.k8s.emberstack.com/reflected-version: "0"
    reflector.v1.k8s.emberstack.com/reflects: docker-registry-secrets/ghcr-credentials

type: kubernetes.io/dockerconfigjson

data:
  .dockerconfigjson: eyJhdXRocyI6e319
