apiVersion: batch/v1
kind: Job

metadata:
  name: migration
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"

spec:
  backoffLimit: 3
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-credentials
      restartPolicy: OnFailure
      containers:
        - name: migration
          image: ghcr.io/rokoucha/sophie-migrate:20260730.160740
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgresql-app
                  key: uri
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
      securityContext:
        seccompProfile:
          type: RuntimeDefault
