apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: ml-models
  annotations:
    argocd.argoproj.io/sync-wave: "0"

spec:
  accessModes:
    - ReadWriteMany
  storageClassName: beryllium-nfs
  resources:
    requests:
      storage: 10Gi
