domainFilters:
  - ggrel.net

labelFilter: external-dns.rokoucha.com/scope=teamspeak

annotationPrefix: teamspeak.external-dns.alpha.kubernetes.io/

managedRecordTypes:
  - AAAA

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-key
        key: apiKey

policy: sync

txtOwnerId: materia-teamspeak-aaaa

logLevel: debug

provider:
  name: cloudflare

sources:
  - service
