sources:
  - service

domainFilters:
  - ggrel.net

labelFilter: external-dns.rokoucha.com/scope=lb-test

annotationPrefix: lb-test.external-dns.alpha.kubernetes.io/

managedRecordTypes:
  - A

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-key
        key: apiKey

extraArgs:
  - --default-targets=175.177.69.46
  - --force-default-targets

policy: sync

txtOwnerId: materia-lb-test

logLevel: debug

provider:
  name: cloudflare
