apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

resources:
  - ./resources/deployment.yaml
  - ./resources/grafana-secrets.yaml
  - ./resources/ingress.yaml
  - ./resources/namespace.yaml
  - ./resources/persistent-volume-claim.yaml
  - ./resources/service.yaml
  - ./resources/tls.yaml

configMapGenerator:
  - name: config
    envs:
      - ./config/config.env
