image:
  tag: "13.1.0"

deploymentStrategy:
  type: Recreate

annotations:
  argocd.argoproj.io/sync-options: Replace=true

env:
  GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "true"

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000
  ipFamilyPolicy: RequireDualStack
  ipFamilies:
    - IPv4
    - IPv6

ingress:
  enabled: true
  ingressClassName: haproxy
  hosts:
    - monitor.ggrel.net
  tls:
    - secretName: tls
      hosts:
        - monitor.ggrel.net

resources:
  requests:
    cpu: 250m
    memory: 750Mi

persistence:
  enabled: true
  existingClaim: data

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://loki-gateway.loki.svc.materia-cluster.ggrel.net
        isDefault: false
      - name: Tempo
        uid: tempo
        type: tempo
        access: proxy
        url: http://tempo.tempo.svc.materia-cluster.ggrel.net:3200
        isDefault: false
        jsonData:
          tracesToLogsV2:
            datasourceUid: loki
            tags:
              - key: service.name
                value: service_name
            filterByTraceID: false
            filterBySpanID: false
            customQuery: true
            query: '{service_name="postgresql", service_namespace="sophie"} |= "$${__trace.traceId}"'
            spanStartTimeShift: -15m
            spanEndTimeShift: 15m

envFromSecrets:
  - name: grafana-secrets

envFromConfigMaps:
  - name: config

testFramework:
  enabled: false
