apiVersion: monitoring.coreos.com/v1
kind: PodMonitor

metadata:
  name: cloudnative-pg-monitor
  namespace: cnpg-system

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudnative-pg
  podMetricsEndpoints:
    - port: metrics
