apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mackerel-operator

helmCharts:
  - name: mackerel-operator
    releaseName: mackerel-operator
    namespace: mackerel-operator
    version: "0.4.1"
    repo: https://slashnephy.github.io/mackerel-operator
    includeCRDs: true
    valuesInline:
      mackerel:
        apiKeySecret:
          name: mackerel-apikey
          key: MACKEREL_APIKEY
      policy: sync
      ownerID: materia
      agentInjector:
        enabled: true

resources:
  - ./resources/network-policy.yaml
  - ./resources/mackerel-apikey.yaml
  - ./resources/namespace.yaml

patches:
  - target:
      kind: Deployment|Role|RoleBinding|ServiceAccount
      labelSelector: app.kubernetes.io/instance=mackerel-operator
    patch: |-
      - op: add
        path: /metadata/namespace
        value: mackerel-operator
