apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus

resources:
  - ./resources/deployment.yaml
  - ./resources/namespace.yaml
  - ./resources/persistent-volume-claim.yaml
  - ./resources/persistent-volume.yaml
  - ./resources/service.yaml

configMapGenerator:
  - name: config
    files:
      - ./config/prometheus.yml
