apiVersion: mackerel.starry.blue/v1alpha1
kind: ExternalMonitor

metadata:
  name: authentik

spec:
  name: authentik
  service: Ggrel
  url: https://auth.ggrel.net/-/health/ready/
  expectedStatusCode: 200
  maxCheckAttempts: 3
  responseTimeDuration: 3
  responseTimeWarning: 5000
  responseTimeCritical: 10000
  certificationExpirationWarning: 7
  certificationExpirationCritical: 3
