apiVersion: monitoring.coreos.com/v1
kind: PodMonitor

metadata:
  name: authentik

spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: authentik
      app.kubernetes.io/name: authentik
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      relabelings:
        - targetLabel: job
          replacement: authentik
