apiVersion: v1
kind: PersistentVolume

metadata:
  name: pvc-0d79abed-4876-4d85-a2e1-14edb751c5c7

spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: postgresql-1
    namespace: authentik
  csi:
    driver: csi.san.synology.com
    fsType: btrfs
    volumeAttributes:
      baseDir: ""
      dsm: 172.16.2.17
      formatOptions: --nodiscard
      mountPermissions: ""
      protocol: iscsi
      source: ""
    volumeHandle: 76ca4738-69b7-4249-8bee-8c64a380df1d
  persistentVolumeReclaimPolicy: Retain
  storageClassName: beryllium-iscsi
  volumeMode: Filesystem
