apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector

metadata:
  name: otelcol-external

spec:
  config:
    extensions:
      bearertokenauth:
        token: ${env:OTEL_BEARER_TOKEN}

    receivers:
      otlp:
        protocols:
          grpc:
            auth:
              authenticator: bearertokenauth
          http:
            auth:
              authenticator: bearertokenauth
      prometheus/self:
        config:
          scrape_configs:
            - job_name: opentelemetry-collector
              scrape_interval: 10s
              static_configs:
                - targets: ["0.0.0.0:8888"]

    processors:
      memory_limiter:
        check_interval: 1s
        limit_mib: 256
        spike_limit_mib: 64
      batch: {}
      resource/source:
        attributes:
          - key: telemetry.source
            value: external
            action: upsert
      resource/append_pod_ip:
        attributes:
          - key: k8s.pod.ip
            action: insert
            value: ${env:MY_POD_IP}
      resource/remove_k8s_pod_ip:
        attributes:
          - key: k8s.pod.ip
            action: delete
      transform/add_sample_key:
        error_mode: ignore
        log_statements:
          - set(log.attributes["_sample_key"], UUID())
      probabilistic_sampler/logs:
        sampling_percentage: 10
        mode: hash_seed
        attribute_source: record
        from_attribute: _sample_key
        hash_seed: 12345
        fail_closed: true
      transform/remove_sample_key:
        error_mode: ignore
        log_statements:
          - delete_key(log.attributes, "_sample_key")
    exporters:
      mackerel_otlp: {}
      otlp_grpc:
        endpoint: otelcol-gateway-collector-headless.monitoring.svc.materia-cluster.ggrel.net:4317
        tls:
          insecure: true
      otlp_http/prometheus:
        metrics_endpoint: http://prometheus-operated.prometheus.svc.materia-cluster.ggrel.net:9090/api/v1/otlp/v1/metrics
      otlp_http/loki:
        endpoint: http://loki-gateway.loki.svc.materia-cluster.ggrel.net/otlp
        tls:
          insecure: true
      otlp_grpc/tempo:
        endpoint: tempo.tempo.svc.materia-cluster.ggrel.net:4317
        tls:
          insecure: true
    service:
      extensions:
        - bearertokenauth
      pipelines:
        metrics/self:
          receivers:
            - prometheus/self
          processors:
            - resource/append_pod_ip
          exporters:
            - otlp_grpc
        metrics:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - resource/source
            - resource/remove_k8s_pod_ip
            - batch
          exporters:
            - mackerel_otlp
            - otlp_http/prometheus
        traces:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - resource/source
            - resource/remove_k8s_pod_ip
            - batch
          exporters:
            - mackerel_otlp
            - otlp_grpc/tempo
        logs:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - resource/source
            - resource/remove_k8s_pod_ip
            - batch
          exporters:
            - otlp_http/loki
        logs/mackerel:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - resource/source
            - resource/remove_k8s_pod_ip
            - transform/add_sample_key
            - probabilistic_sampler/logs
            - transform/remove_sample_key
          exporters:
            - mackerel_otlp

  envFrom:
    - secretRef:
        name: mackerel-apikey
  env:
    - name: OTEL_BEARER_TOKEN
      valueFrom:
        secretKeyRef:
          name: otelcol-external-token
          key: OTEL_BEARER_TOKEN
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP

  image: ghcr.io/rokoucha/otelcol/materia-external:20260716.153940
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: RequireDualStack
  mode: deployment
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
  replicas: 1
