apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector

metadata:
  name: otelcol-external

spec:
  config:
    extensions:
      bearertokenauth:
        token: ${env:OTEL_BEARER_TOKEN}

    receivers:
      otlp:
        protocols:
          http:
            auth:
              authenticator: bearertokenauth
      prometheus/self:
        config:
          scrape_configs:
            - job_name: opentelemetry-collector
              scrape_interval: 10s
              static_configs:
                - targets: ["0.0.0.0:8888"]

    processors:
      memory_limiter:
        check_interval: 1s
        limit_mib: 256
        spike_limit_mib: 64
      batch: {}
      resource/source:
        attributes:
          - key: telemetry.source
            value: external
            action: upsert
      resource/append_pod_ip:
        attributes:
          - key: k8s.pod.ip
            action: insert
            value: ${env:MY_POD_IP}
      resource/remove_k8s_pod_ip:
        attributes:
          - key: k8s.pod.ip
            action: delete
      transform/add_sample_key:
        error_mode: ignore
        log_statements:
          - set(log.attributes["_sample_key"], UUID())
      probabilistic_sampler/logs:
        sampling_percentage: 10
        mode: hash_seed
        attribute_source: record
        from_attribute: _sample_key
        hash_seed: 12345
        fail_closed: true
      transform/remove_sample_key:
        error_mode: ignore
        log_statements:
          - delete_key(log.attributes, "_sample_key")
      batch/mackerel_logs:
        send_batch_size: 1000
        send_batch_max_size: 1000
        timeout: 1s

    exporters:
      mackerelotlp: {}
      otlp:
        endpoint: otelcol-gateway-collector-headless.monitoring.svc.materia-cluster.ggrel.net:4317
        tls:
          insecure: true
      otlphttp/prometheus:
        metrics_endpoint: http://prometheus-operated.prometheus.svc.materia-cluster.ggrel.net:9090/api/v1/otlp/v1/metrics
      otlphttp/loki:
        endpoint: http://loki-gateway.loki.svc.materia-cluster.ggrel.net/otlp
        tls:
          insecure: true
      otlp/tempo:
        endpoint: tempo.tempo.svc.materia-cluster.ggrel.net:4317
        tls:
          insecure: true
      otlphttp/mackerel_logs:
        logs_endpoint: https://otlp-vaxila.mackerelio.com/v1/logs
        headers:
          Mackerel-Api-Key: ${env:MACKEREL_APIKEY}
          Accept: "*/*"

    service:
      extensions:
        - bearertokenauth
      pipelines:
        metrics/self:
          receivers:
            - prometheus/self
          processors:
            - resource/append_pod_ip
          exporters:
            - otlp
        metrics:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - resource/source
            - resource/remove_k8s_pod_ip
            - batch
          exporters:
            - mackerelotlp
            - otlphttp/prometheus
        traces:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - resource/source
            - resource/remove_k8s_pod_ip
            - batch
          exporters:
            - mackerelotlp
            - otlp/tempo
        logs:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - resource/source
            - resource/remove_k8s_pod_ip
            - batch
          exporters:
            - otlphttp/loki
        logs/mackerel:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - resource/source
            - resource/remove_k8s_pod_ip
            - transform/add_sample_key
            - probabilistic_sampler/logs
            - transform/remove_sample_key
            - batch/mackerel_logs
          exporters:
            - otlphttp/mackerel_logs

  envFrom:
    - secretRef:
        name: mackerel-apikey
  env:
    - name: OTEL_BEARER_TOKEN
      valueFrom:
        secretKeyRef:
          name: otelcol-external-token
          key: OTEL_BEARER_TOKEN
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP

  image: ghcr.io/rokoucha/otelcol/materia-external:20260701.123135
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: RequireDualStack
  mode: deployment
  replicas: 1
