apiVersion: apps/v1
kind: Deployment

metadata:
  name: controller-manager

spec:
  template:
    spec:
      volumes:
        - name: webhook-cert
          secret:
            secretName: loki-operator-webhook-server-cert
