apiVersion: batch/v1
kind: CronJob

metadata:
  name: mastodon-media-remove

spec:
  schedule: 0 4 * * 0
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: ghcr.io/mastodon/mastodon:v4.5.3
              name: mastodon-media-remove
              command:
                [
                  "bin/tootctl",
                  "media",
                  "remove",
                  "--days",
                  "7",
                  "--concurrency",
                  "10",
                ]
              env:
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: postgresql-app
                      key: host
                - name: DB_PORT
                  valueFrom:
                    secretKeyRef:
                      name: postgresql-app
                      key: port
                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: postgresql-app
                      key: dbname
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgresql-app
                      key: username
                - name: DB_PASS
                  valueFrom:
                    secretKeyRef:
                      name: postgresql-app
                      key: password
              envFrom:
                - configMapRef:
                    name: config
                - secretRef:
                    name: mastodon-secrets
          restartPolicy: OnFailure
