apiVersion: batch/v1
kind: CronJob

metadata:
  name: mastodon-media-remove

spec:
  schedule: 0 4 * * 0
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: ghcr.io/mastodon/mastodon:v4.4.4
              name: mastodon-media-remove
              command:
                [
                  "bin/tootctl",
                  "media",
                  "remove",
                  "--days",
                  "7",
                  "--concurrency",
                  "10",
                ]
              envFrom:
                - configMapRef:
                    name: config
                - secretRef:
                    name: mastodon-secrets
          restartPolicy: OnFailure
