apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: elasticsearch-data-elasticsearch-es-default-0

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: beryllium-iscsi
  volumeMode: Filesystem
  volumeName: pvc-7c391557-b7b8-4ea2-b21a-582c3b2c6c79
