apiVersion: batch/v1
kind: Job

metadata:
  name: mastodon-deploy-search

spec:
  backoffLimit: 3
  parallelism: 1
  completions: 1
  template:
    spec:
      containers:
        - image: ghcr.io/mastodon/mastodon:v4.5.3
          name: mastodon-migration
          command: ["bin/tootctl", "search", "deploy"]
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: postgresql-app
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: postgresql-app
                  key: port
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgresql-app
                  key: dbname
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-app
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgresql-app
                  key: password
            - name: ES_PASS
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-es-elastic-user
                  key: elastic
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: k8s.pod.ip=${env:MY_POD_IP}
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          envFrom:
            - configMapRef:
                name: config
            - secretRef:
                name: mastodon-secrets
      restartPolicy: OnFailure
