apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector

metadata:
  name: otelcol

spec:
  config:
    receivers:
      otlp:
        protocols:
          http: {}
      prometheus:
        config:
          scrape_configs:
            - job_name: otel-collector
              scrape_interval: 10s
              static_configs:
                - targets: ["0.0.0.0:8888"]

    processors:
      memory_limiter:
        check_interval: 1s
        limit_mib: 2000
        spike_limit_mib: 500
      probabilistic_sampler:
        sampling_percentage: 1

    exporters:
      debug:
        verbosity: normal
      otlp:
        endpoint: otelcol-gateway-collector.opentelemetry-collector.svc.materia-cluster.ggrel.net:4317
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, probabilistic_sampler]
          exporters: [otlp]
        metrics:
          receivers: [otlp, prometheus]
          processors: [memory_limiter]
          exporters: [otlp]
      telemetry:
        resource:
          service.name: mastsodon/otelcol
  image: ghcr.io/rokoucha/otelcol/materia-mastodon:sha-aa79f59
  mode: statefulset
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: RequireDualStack
  targetAllocator:
    enabled: true
    prometheusCR:
      enabled: true
      allowNamespaces:
        - mastodon
      podMonitorSelector: {}
      serviceMonitorSelector: {}
