apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector

metadata:
  name: otelcol

spec:
  mode: statefulset
  targetAllocator:
    enabled: true
    prometheusCR:
      enabled: true
      podMonitorSelector: {}
  config:
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
      prometheus:
        config:
          scrape_configs:
            - job_name: otel-collector
              scrape_interval: 10s
              static_configs:
                - targets: ["0.0.0.0:8888"]

    exporters:
      debug:
        verbosity: normal

    service:
      pipelines:
        metrics:
          receivers: [otlp, prometheus]
          exporters: [debug]
      telemetry:
        resource:
          service.name: mastsodon/otelcol

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: opentelemetry-targetallocator-role

rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/metrics
      - services
      - endpoints
      - pods
      - namespaces
    verbs: ["get", "list", "watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["monitoring.coreos.com"]
    resources:
      - podmonitors
      - probes
      - scrapeconfigs
      - servicemonitors
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: opentelemetry-targetallocator-rb

subjects:
  - kind: ServiceAccount
    name: otelcol-targetallocator
    namespace: mastodon
roleRef:
  kind: ClusterRole
  name: opentelemetry-targetallocator-role
  apiGroup: rbac.authorization.k8s.io
