apiVersion: postgresql.cnpg.io/v1
kind: Cluster

metadata:
  name: postgresql

spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1-minimal-trixie
  instances: 1
  bootstrap:
    initdb:
      database: mastodon
      import:
        type: microservice
        databases:
          - mastodon
        source:
          externalCluster: materia
  storage:
    size: 10Gi
  externalClusters:
    - name: materia
      connectionParameters:
        host: service.postgresql.svc.materia-cluster.ggrel.net
        user: postgres
        dbname: mastodon
      password:
        name: materia-postgresql-password
        key: password
