apiVersion: postgresql.cnpg.io/v1
kind: Cluster

metadata:
  name: postgresql

spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1-minimal-trixie
  instances: 1
  postgresql:
    parameters:
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
  bootstrap:
    initdb:
      database: mastodon
  storage:
    storageClass: beryllium-iscsi
    size: 10Gi
