apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: redis-data

spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: beryllium-iscsi
  volumeMode: Filesystem
  volumeName: pvc-8284ffb0-47c9-4207-8068-1f1a79369206
