apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis

metadata:
  name: redis

spec:
  kubernetesConfig:
    image: quay.io/opstree/redis:v8.4.0
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
