apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis

metadata:
  name: redis

spec:
  kubernetesConfig:
    image: quay.io/opstree/redis:v8.4.2
  redisExporter:
    enabled: true
    image: quay.io/opstree/redis-exporter:v1.81.0
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
