apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: redis-monitor

spec:
  selector:
    matchLabels:
      redis_setup_type: standalone
  endpoints:
    - port: redis-exporter
      interval: 30s
      scrapeTimeout: 10s
