apiVersion: monitoring.coreos.com/v1
kind: PodMonitor

metadata:
  name: redis-operator-monitor

spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      name: redis-operator
  podTargetLabels:
    - name
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      scheme: http
      interval: 30s
      scrapeTimeout: 10s
