apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: argocd-github-app
  labels:
    argocd.argoproj.io/secret-type: repo-creds
spec:
  itemPath: vaults/ct5helkweamxgoqur2sfafw43u/items/bvyvg4wzv2s4k53ghnfebufzsa
