apiVersion: apps/v1
kind: Deployment

metadata:
  name: deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      labels:
        app: default
    spec:
      containers:
        - name: snmp-exporter
          image: quay.io/prometheus/snmp-exporter:v0.26.0
          args:
            - --config.file=/snmp.yml
          ports:
            - containerPort: 9116
          volumeMounts:
            - name: snmp-config
              mountPath: /snmp.yml
              subPath: snmp.conf
              readOnly: true
      volumes:
        - name: snmp-config
          configMap:
            name: snmp-config
