apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: default-deny-egress
spec:
  endpointSelector:
    matchExpressions:
      - key: k8s:io.kubernetes.pod.namespace
        operator: Exists
      - key: k8s:io.kubernetes.pod.namespace
        operator: NotIn
        values:
          - actions-runner
          - argocd
          - authentik
          - haproxy-controller
          - kube-system
          - mahiron
          - mastodon
          - mirakurun
          - monitoring
          - otel-external
          - sophie
          - tailscale
          - teamspeak
  enableDefaultDeny:
    egress: true
    ingress: false
  egress:
    - {}
