apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: actions-runner

resources:
  - ./resources/namespace.yaml
  - ./resources/priority-class.yaml
  - ./resources/runner-state.yaml
  - ./resources/pnpm-store.yaml
  - ./resources/deployment.yaml
