apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: pix-smb400-gateway-state

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: beryllium-iscsi
