apiVersion: v1
kind: ConfigMap

metadata:
  name: argocd-notifications-cm

data:
  context: |
    argocdUrl: https://argocd.materia.ggrel.net

  defaultTriggers: |
    - on-deployed
    - on-health-degraded
    - on-health-unknown
    - on-sync-failed
    - on-sync-running

  subscriptions: |
    - recipients:
        - github
      triggers:
        - on-deployed
        - on-sync-failed
        - on-sync-running
    - recipients:
        - discord
      triggers:
        - on-health-degraded
        - on-health-unknown

  service.github: |
    appID: 980715
    installationID: 54216756
    privateKey: $github-privateKey

  service.webhook.discord: |
    url: $discord-webhookUrl
    headers:
      - name: Content-Type
        value: application/json

  template.discord-health-degraded: |
    webhook:
      discord:
        method: POST
        body: |
          {
            "username": "Argo CD",
            "embeds": [
              {
                "color": 14036256,
                "title": "{{.app.metadata.name}}",
                "description": "Application health is now **{{.app.status.health.status}}**.",
                "url": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
                "fields": [
                  {
                    "name": "Health",
                    "value": "{{.app.status.health.status}}",
                    "inline": true
                  },
                  {
                    "name": "Sync",
                    "value": "{{.app.status.sync.status}}",
                    "inline": true
                  }
                ]
              }
            ]
          }

  template.discord-health-unknown: |
    webhook:
      discord:
        method: POST
        body: |
          {
            "username": "Argo CD",
            "embeds": [
              {
                "color": 16754432,
                "title": "{{.app.metadata.name}}",
                "description": "Application health is now **{{.app.status.health.status}}**.",
                "url": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
                "fields": [
                  {
                    "name": "Health",
                    "value": "{{.app.status.health.status}}",
                    "inline": true
                  },
                  {
                    "name": "Sync",
                    "value": "{{.app.status.sync.status}}",
                    "inline": true
                  }
                ]
              }
            ]
          }

  template.github-success: |
    message: Application {{.app.metadata.name}} is now running new version of deployments manifests.
    github:
      status:
        state: success
        label: "CD/{{.app.metadata.name}}"
        targetURL: "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"

  template.github-failed: |
    message: Application {{.app.metadata.name}} sync failed.
    github:
      status:
        state: failure
        label: "CD/{{.app.metadata.name}}"
        targetURL: "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"

  template.github-running: |
    message: Application {{.app.metadata.name}} is syncing.
    github:
      status:
        state: pending
        label: "CD/{{.app.metadata.name}}"
        targetURL: "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"

  trigger.on-deployed: |
    - when: app.status.operationState != nil and app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
      oncePer: app.status.operationState.syncResult.revision
      send: [github-success]

  trigger.on-health-degraded: |
    - when: app.status.health.status == 'Degraded' and app.status.sync.status == 'Synced'
      oncePer: app.status.sync.revision
      send: [discord-health-degraded, github-failed]

  trigger.on-sync-failed: |
    - when: app.status.operationState != nil and app.status.operationState.phase in ['Failed', 'Error']
      oncePer: app.status.operationState.syncResult.revision
      send: [github-failed]

  trigger.on-sync-running: |
    - when: app.status.operationState != nil and app.status.operationState.phase in ['Running']
      oncePer: app.status.operationState.syncResult.revision
      send: [github-running]

  trigger.on-health-unknown: |
    - when: app.status.health.status == 'Unknown' and app.status.sync.status == 'Synced'
      oncePer: app.status.sync.revision
      send: [discord-health-unknown]
