apiVersion: v1
kind: ConfigMap

metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm

data:
  url: https://argocd.materia.ggrel.net
  dex.config: |
    connectors:
      - type: oidc
        id: authentik
        name: authentik
        config:
          issuer: https://auth.ggrel.net/application/o/materia-argocd/
          clientID: TrkjevcCNKOaFluWdtpE3A7siE3XwlnzI9IdMbds
          clientSecret: $dex.authentik.clientSecret
          insecureEnableGroups: true
          scopes:
            - openid
            - profile
            - email
  resource.customizations: |
    networking.k8s.io/Ingress:
      health.lua: |
        hs = {}
        hs.status = "Healthy"
        hs.message = "Probably just fine"
        return hs
  resource.exclusions: |
    - apiGroups:
        - cilium.io
      kinds:
        - CiliumIdentity
      clusters:
        - "*"
  kustomize.buildOptions: --enable-helm --load-restrictor LoadRestrictionsNone
  admin.enabled: "false"
