apiVersion: v1
kind: ConfigMap

metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm

data:
  url: https://argocd.materia.ggrel.net
  accounts.mcp-bot: apiKey
  oidc.config: |
    name: authentik
    issuer: https://auth.ggrel.net/application/o/argo-cd/
    clientID: 48oKkchh0jq5I1GccvwDtrFcUANjtu8MqnTFmH4O
    enablePKCEAuthentication: true
    requestedScopes:
      - openid
      - profile
      - email
      - offline_access
    requestedIDTokenClaims:
      groups:
        essential: true
    refreshTokenThreshold: 30s
  resource.customizations: |
    networking.k8s.io/Ingress:
      health.lua: |
        hs = {}
        hs.status = "Healthy"
        hs.message = "Probably just fine"
        return hs
  resource.customizations.health.argoproj.io_Application: |
    hs = {}
    hs.status = "Progressing"
    hs.message = ""
    if obj.status ~= nil then
      if obj.status.health ~= nil then
        hs.status = obj.status.health.status
        if obj.status.health.message ~= nil then
          hs.message = obj.status.health.message
        end
      end
    end
    return hs
  resource.exclusions: |
    - apiGroups:
        - cilium.io
      kinds:
        - CiliumIdentity
      clusters:
        - "*"
  kustomize.buildOptions: --enable-helm --load-restrictor LoadRestrictionsNone
  admin.enabled: "true"
