apiVersion: v1
kind: ConfigMap

metadata:
  name: argocd-rbac-cm
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd

data:
  policy.csv: |
    g, authentik Admins, role:admin
    g, authentik Read-only, role:readonly
