apiVersion: v1alpha1
kind: HostnameConfig
auto: 'off'
hostname: lithium
---
apiVersion: v1alpha1
kind: LinkAliasConfig
name: ethSel0
selector:
  match: link.type == 1
---
apiVersion: v1alpha1
kind: Layer2VIPConfig
name: 172.16.2.20
link: ethSel0
---
apiVersion: v1alpha1
kind: LinkConfig
name: ethSel0
addresses:
  - address: 172.16.2.22/24
routes:
  - gateway: 172.16.2.1
---
apiVersion: v1alpha1
kind: VLANConfig
name: ethSel0.30
vlanID: 30
parent: ethSel0
addresses:
  - address: 172.16.3.22/24
  - address: 240b:10:3f6d:1403::22/64
