apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sophie

resources:
  - ./resources/config-map-google-application-credentials.yaml
  - ./resources/elasticsearch.yaml
  - ./resources/ghcr-credentials.yaml
  - ./resources/ingress.yaml
  - ./resources/namespace.yaml
  - ./resources/postgresql.yaml
  - ./resources/redis.yaml
  - ./resources/secrets.yaml
  - ./resources/tls.yaml

