apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: cert-manager

spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: cert-manager
  endpoints:
    - port: http-metrics
