apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: cert-manager
  namespace: cert-manager

spec:
  selector:
    matchLabels:
      app: cert-manager
  endpoints:
    - port: http-metrics

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: cert-manager-cainjector
  namespace: cert-manager

spec:
  selector:
    matchLabels:
      app: cainjector
  endpoints:
    - port: http-metrics

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: cert-manager-webhook
  namespace: cert-manager

spec:
  selector:
    matchLabels:
      app: webhook
  endpoints:
    - port: http-metrics
