apiVersion: v1
kind: PersistentVolume

metadata:
  name: pvc-5a02e06b-2e7b-45fe-9873-5a4629412ee3

spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: postgresql-1
    namespace: miniflux
  csi:
    driver: csi.san.synology.com
    fsType: btrfs
    volumeAttributes:
      baseDir: ""
      dsm: 172.16.2.17
      formatOptions: --nodiscard
      mountPermissions: ""
      protocol: iscsi
      source: ""
    volumeHandle: 11844839-4572-4042-ac42-4f5f10f48b66
  persistentVolumeReclaimPolicy: Retain
  storageClassName: beryllium-iscsi
  volumeMode: Filesystem
