apiVersion: postgresql.cnpg.io/v1
kind: Cluster

metadata:
  name: postgresql

spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1-minimal-trixie
  instances: 1
  bootstrap:
    initdb:
      database: miniflux
  storage:
    storageClass: beryllium-iscsi
    size: 5Gi
