apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres-exporter

resources:
  - ./resources/deployment.yaml
  - ./resources/namespace.yaml
  - ./resources/service.yaml

configMapGenerator:
  - name: snmp-config
    files:
      - ./config/snmp.yml
