apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: external-dns

spec:
  destination:
    server: https://kubernetes.default.svc
  project: system
  source:
    path: system/external-dns
    repoURL: https://github.com/rokoucha/materia.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
