apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: github-actions-runner

spec:
  destination:
    server: https://kubernetes.default.svc
  project: system
  source:
    path: system/github-actions-runner
    repoURL: https://github.com/rokoucha/materia.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
