apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: prometheus-operator

spec:
  destination:
    server: https://kubernetes.default.svc
  project: system
  source:
    path: system/prometheus-operator
    repoURL: https://github.com/rokoucha/materia.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
