apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: influxdb

spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - image: docker.io/library/influxdb:2.8.0-alpine
          name: influxdb
          ports:
            - name: http
              containerPort: 8086
          volumeMounts:
            - name: data
              mountPath: /var/lib/influxdb2
          livenessProbe:
            httpGet:
              path: /health
              port: http
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
      restartPolicy: Always
