apiVersion: ingress.v3.haproxy.org/v3
kind: ValidationRules

metadata:
  name: materia-annotations

spec:
  prefix: materia.ggrel.net
  validation_rules:
    forward-auth:
      section: backend
      type: bool
      rule: value == true
      template: |
        http-request lua.materia-forward-auth
        http-request redirect code 302 location %[var(txn.materia_auth_location)] if { var(txn.materia_auth_result) -m str unauthorized }
        http-request deny deny_status 403 if { var(txn.materia_auth_result) -m str forbidden }
        http-request deny deny_status 503 if { var(txn.materia_auth_result) -m str error }
        http-response set-header X-Materia-Auth-Result %[var(txn.materia_auth_result)] if { var(txn.materia_auth_result) -m found }
        http-response set-header X-Materia-Auth-Status %[var(txn.materia_auth_status)] if { var(txn.materia_auth_status) -m found }
        http-response set-header X-Materia-Auth-Reason %[var(txn.materia_auth_reason)] if { var(txn.materia_auth_reason) -m found }
        http-response add-header Set-Cookie %[var(txn.materia_auth_set_cookie)] if { var(txn.materia_auth_set_cookie) -m found }
