apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ./apcupsd.yaml
  - ./grafana.yaml
  - ./influxdb.yaml
  - ./lb-test.yaml
  - ./loki.yaml
  - ./mastodon.yaml
  - ./miniflux.yaml
  - ./nginx.yaml
  - ./oauth2-proxy.yaml
  - ./otel-external.yaml
  - ./prometheus.yaml
  - ./switchbot-meter-exporter.yaml
  - ./tempo.yaml
  - ./teamspeak.yaml
