apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ./apcupsd-exporter.yaml
  - ./authentik.yaml
  - ./grafana.yaml
  - ./influxdb.yaml
  - ./mastodon.yaml
  - ./miniflux.yaml
  - ./nebraska.yaml
  - ./nginx.yaml
  - ./oauth2-proxy.yaml
  - ./opentelemetry-collector.yaml
  - ./snmp-exporter.yaml
  - ./switchbot-meter-exporter.yaml
  - ./teamspeak.yaml
