apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: mastodon

spec:
  destination:
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - jsonPointers:
        - /data/tls.crt
        - /data/tls.key
        - /metadata/annotations/reflector.v1.k8s.emberstack.com~1reflected-at
        - /metadata/annotations/reflector.v1.k8s.emberstack.com~1reflected-version
      kind: Secret
      name: tls
  project: applications
  source:
    path: applications/mastodon
    repoURL: https://github.com/rokoucha/materia.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
