apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: switchbot-meter-exporter

spec:
  destination:
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: applications/switchbot-meter-exporter
    repoURL: https://github.com/rokoucha/materia.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
