apiVersion: apps/v1
kind: Deployment

metadata:
  name: deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: default
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: default
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - image: docker.io/library/postgres:18.0
          name: postgresql
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-password
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
                - -d
                - postgres
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
      restartPolicy: Always
