apiVersion: v1
kind: PersistentVolume

metadata:
  name: pvc-ae1867dd-7c2d-42a6-996e-ef21272d545e

spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 20Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data
    namespace: postgresql
  csi:
    driver: csi.san.synology.com
    fsType: btrfs
    volumeAttributes:
      baseDir: ""
      dsm: 172.16.2.17
      formatOptions: --nodiscard
      mountPermissions: ""
      protocol: iscsi
      source: ""
      storage.kubernetes.io/csiProvisionerIdentity: 1740323674035-8081-csi.san.synology.com
    volumeHandle: c3e60dd7-0cef-4b93-861f-a6a0f60cd993
  persistentVolumeReclaimPolicy: Delete
  storageClassName: beryllium-iscsi
  volumeMode: Filesystem
