machine:
  kernel:
    modules:
      - name: btrfs
  systemDiskEncryption:
    state:
      provider: luks2
      keys:
        - slot: 0
          tpm: {}
    ephemeral:
      provider: luks2
      keys:
        - slot: 0
          tpm: {}
---
apiVersion: v1alpha1
kind: KubeProxyConfig
enabled: false
---
apiVersion: v1alpha1
kind: KubeAPIServerConfig
extraArgs:
  service-node-port-range: "80-32767"
---
apiVersion: v1alpha1
kind: KubeControllerManagerConfig
extraArgs:
  allocate-node-cidrs: "false"
