apiVersion: v1
kind: PersistentVolume

metadata:
  name: pvc-4e55ad3a-6dfd-49a7-8701-35f94bca49fe

spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data
    namespace: grafana
    resourceVersion: "34463"
    uid: 4e55ad3a-6dfd-49a7-8701-35f94bca49fe
  csi:
    driver: csi.san.synology.com
    fsType: btrfs
    volumeAttributes:
      baseDir: ""
      dsm: 172.16.2.17
      formatOptions: --nodiscard
      mountPermissions: ""
      protocol: iscsi
      source: ""
      storage.kubernetes.io/csiProvisionerIdentity: 1740323674035-8081-csi.san.synology.com
    volumeHandle: b8fba46a-e3d1-4155-b827-6fa51d9f6de8
  persistentVolumeReclaimPolicy: Delete
  storageClassName: beryllium-iscsi
  volumeMode: Filesystem
