apiVersion: loki.grafana.com/v1
kind: LokiStack

metadata:
  name: loki

spec:
  size: 1x.small
  storage:
    schemas:
      - version: v13
        effectiveDate: "2026-01-05"
    secret:
      name: loki-storage-secret
      type: s3
  storageClassName: beryllium-nfs
