apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector

metadata:
  name: otelcol-external

spec:
  config:
    extensions:
      bearertokenauth:
        token: ${env:OTEL_BEARER_TOKEN}

    receivers:
      otlp:
        protocols:
          http:
            auth:
              authenticator: bearertokenauth
      prometheus/self:
        config:
          scrape_configs:
            - job_name: opentelemetry-collector
              scrape_interval: 10s
              static_configs:
                - targets: ["0.0.0.0:8888"]

    processors:
      memory_limiter:
        check_interval: 1s
        limit_mib: 256
        spike_limit_mib: 64
      batch: {}
      resource/source:
        attributes:
          - key: telemetry.source
            value: external
            action: upsert
      resource/append_pod_ip:
        attributes:
          - key: k8s.pod.ip
            action: insert
            value: ${env:MY_POD_IP}

    exporters:
      otlp:
        endpoint: otelcol-gateway-collector-headless.monitoring.svc.materia-cluster.ggrel.net:4317
        tls:
          insecure: true

    connectors:
      routing/metrics:
        table:
          - condition: "true"
            pipelines:
              - metrics

    service:
      extensions:
        - bearertokenauth
      pipelines:
        metrics/self:
          receivers:
            - prometheus/self
          processors:
            - resource/append_pod_ip
          exporters:
            - routing/metrics
        metrics:
          receivers:
            - routing/metrics
            - otlp
          processors:
            - memory_limiter
            - resource/source
            - batch
          exporters:
            - otlp
        traces:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - resource/source
            - batch
          exporters:
            - otlp
        logs:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - resource/source
            - batch
          exporters:
            - otlp

  env:
    - name: OTEL_BEARER_TOKEN
      valueFrom:
        secretKeyRef:
          name: otelcol-external-token
          key: OTEL_BEARER_TOKEN
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP

  image: ghcr.io/rokoucha/otelcol/materia-external:20260414.101702
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: RequireDualStack
  mode: deployment
  replicas: 1
