apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otelcol-clusteragent
spec:
  networkPolicy:
    enabled: false
  config:
    receivers:
      k8s_events: {}
      prometheus/self:
        config:
          scrape_configs:
            - job_name: opentelemetry-collector
              scrape_interval: 10s
              static_configs:
                - targets: ["0.0.0.0:8888"]

    processors:
      batch:
        send_batch_size: 1024
        send_batch_max_size: 1024
        timeout: 1s
      memory_limiter:
        check_interval: 1s
        limit_mib: 512
        spike_limit_mib: 128
      resource/append_otelcol_agent_pod_ip:
        attributes:
          - key: k8s.pod.ip
            action: insert
            value: ${env:MY_POD_IP}

    exporters:
      otlp_grpc:
        timeout: 5s
        retry_on_failure:
          max_elapsed_time: 60s
        sending_queue:
          sizer: bytes
          queue_size: 2097152
          num_consumers: 2
          block_on_overflow: false
          wait_for_result: false
          batch:
            sizer: bytes
            min_size: 65536
            max_size: 524288
            flush_timeout: 1s
        endpoint: otelcol-gateway-collector-headless.monitoring.svc.materia-cluster.ggrel.net:4317
        tls:
          insecure: true

    service:
      pipelines:
        logs:
          receivers:
            - k8s_events
          processors:
            - memory_limiter
            - batch
          exporters:
            - otlp_grpc
        metrics:
          receivers:
            - prometheus/self
          processors:
            - memory_limiter
            - batch
            - resource/append_otelcol_agent_pod_ip
          exporters:
            - otlp_grpc
  env:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
  image: ghcr.io/rokoucha/otelcol/materia-clusteragent:20261008.101415
  mode: deployment
  replicas: 1
  serviceAccount: otelcol-clusteragent-sa
