apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector

metadata:
  name: otelcol-gateway

spec:
  config:
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
      prometheus:
        config:
          scrape_configs: []
      prometheus/self:
        config:
          scrape_configs:
            - job_name: opentelemetry-collector
              scrape_interval: 10s
              static_configs:
                - targets: ["0.0.0.0:8888"]

    processors:
      batch: {}
      memory_limiter:
        check_interval: 1s
        limit_mib: 1000
        spike_limit_mib: 256
      k8sattributes:
        auth_type: serviceAccount
        extract:
          metadata:
            - k8s.node.name
            - k8s.namespace.name
            - k8s.deployment.name
            - k8s.daemonset.name
            - k8s.statefulset.name
            - k8s.cronjob.name
            - k8s.job.name
            - k8s.pod.name
            - k8s.pod.start_time
            - k8s.pod.uid
        pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.pod.ip
          - sources:
              - from: resource_attribute
                name: k8s.pod.uid
          - sources:
              - from: connection
      resource/append_otelcol_agent_pod_ip:
        attributes:
          - key: k8s.pod.ip
            action: insert
            value: ${env:MY_POD_IP}
      resource/cluster_name:
        attributes:
          - key: k8s.cluster.name
            value: materia-cluster
            action: upsert
      resource/remove_k8s_pod_ip:
        attributes:
          - key: k8s.pod.ip
            action: delete

    exporters:
      debug:
        verbosity: basic
      mackerelotlp:
        batch:
          max_size: 4_000_000
      otlphttp/prometheus:
        metrics_endpoint: http://prometheus-operated.monitoring.svc.materia-cluster.ggrel.net:9090/api/v1/otlp/v1/metrics

    connectors:
      routing/metrics:
        table:
          - condition: "true"
            pipelines:
              - metrics

    service:
      pipelines:
        logs:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - batch
            - k8sattributes
            - resource/cluster_name
            - resource/remove_k8s_pod_ip
          exporters:
            - debug
        metrics/self:
          receivers:
            - prometheus/self
          processors:
            - resource/append_otelcol_agent_pod_ip
          exporters:
            - routing/metrics
        metrics:
          receivers:
            - routing/metrics
            - otlp
            - prometheus
          processors:
            - memory_limiter
            - batch
            - k8sattributes
            - resource/cluster_name
            - resource/remove_k8s_pod_ip
          exporters:
            - mackerelotlp
            - otlphttp/prometheus
        traces:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - batch
            - k8sattributes
            - resource/cluster_name
            - resource/remove_k8s_pod_ip
          exporters:
            - mackerelotlp
  envFrom:
    - secretRef:
        name: mackerel-apikey
  env:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
  image: ghcr.io/rokoucha/otelcol/materia-gateway:sha-0acb4f1
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: RequireDualStack
  mode: statefulset
  serviceAccount: otelcol-gateway-sa
  targetAllocator:
    allocationStrategy: consistent-hashing
    enabled: true
    prometheusCR:
      enabled: true
      podMonitorSelector: {}
      serviceMonitorSelector: {}
    serviceAccount: otelcol-gateway-ta-sa
