apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: otelcol-agent-role

rules:
  - apiGroups: [""]
    resources:
      - nodes
    verbs:
      - get
      - list
  - apiGroups: [""]
    resources:
      - nodes/stats
    verbs:
      - get
  - apiGroups: [""]
    resources:
      - nodes
    verbs:
      - watch
  - apiGroups: [""]
    resources:
      - nodes/proxy
      - nodes/metrics
    verbs:
      - get
