apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector

metadata:
  name: otelcol-agent

spec:
  config:
    receivers:
      filelog:
        include:
          - /var/log/pods/*/*/*.log
        start_at: end
        include_file_path: true
        include_file_name: false
        operators:
          - type: container
            id: container-parser
      hostmetrics:
        root_path: /hostfs
        scrapers:
          cpu: {}
          memory: {}
          disk: {}
      kubeletstats:
        collection_interval: 10s
        auth_type: serviceAccount
        endpoint: ${env:K8S_NODE_NAME}:10250
        insecure_skip_verify: true
        metric_groups:
          - node
          - pod
          - container
      prometheus/self:
        config:
          scrape_configs:
            - job_name: opentelemetry-collector
              scrape_interval: 10s
              static_configs:
                - targets: ["0.0.0.0:8888"]

    processors:
      batch: {}
      memory_limiter:
        check_interval: 1s
        limit_mib: 512
        spike_limit_mib: 128
      k8sattributes:
        passthrough: true
      resourcedetection:
        detectors:
          - system
          - env
          - k8snode
        timeout: 5s
        override: false
      resource/append_otelcol_agent_pod_ip:
        attributes:
          - key: k8s.pod.ip
            action: insert
            value: ${env:MY_POD_IP}

    exporters:
      otlp:
        endpoint: otelcol-gateway-collector-headless.monitoring.svc.materia-cluster.ggrel.net:4317
        tls:
          insecure: true

    connectors:
      routing/metrics:
        table:
          - condition: "true"
            pipelines:
              - metrics

    service:
      pipelines:
        metrics/self:
          receivers:
            - prometheus/self
          processors:
            - resource/append_otelcol_agent_pod_ip
          exporters:
            - routing/metrics
        metrics:
          receivers:
            - routing/metrics
            - hostmetrics
            - kubeletstats
          processors:
            - k8sattributes
            - resourcedetection
            - memory_limiter
            - batch
          exporters:
            - otlp
        logs:
          receivers:
            - filelog
          processors:
            - k8sattributes
            - resourcedetection
            - memory_limiter
            - batch
          exporters:
            - otlp
  env:
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
  image: ghcr.io/rokoucha/otelcol/materia-agent:sha-7fe7fe8
  mode: daemonset
  replicas: 1
  serviceAccount: otelcol-agent-sa
  volumeMounts:
    - name: hostfs
      mountPath: /hostfs
    - name: varlogpods
      mountPath: /var/log/pods
  volumes:
    - name: hostfs
      hostPath:
        path: /
    - name: varlogpods
      hostPath:
        path: /var/log/pods
