apiVersion: v1
kind: PersistentVolume

metadata:
  name: pvc-2a79df8c-7605-4225-9a79-04330e38d000

spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 30Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: prometheus-prometheus-db-prometheus-prometheus-0
    namespace: monitoring
  csi:
    driver: csi.san.synology.com
    fsType: btrfs
    volumeAttributes:
      baseDir: ""
      dsm: 172.16.2.17
      formatOptions: --nodiscard
      mountPermissions: ""
      protocol: iscsi
      source: ""
    volumeHandle: bac2b55c-933e-404a-88ff-0961ae073619
  persistentVolumeReclaimPolicy: Retain
  storageClassName: beryllium-iscsi
  volumeMode: Filesystem
