apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: prometheus-prometheus-db-prometheus-prometheus-0
  namespace: monitoring

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: beryllium-iscsi
  volumeMode: Filesystem
  volumeName: pvc-2a79df8c-7605-4225-9a79-04330e38d000
