apiVersion: v1
kind: PersistentVolume

metadata:
  name: pvc-2d76d711-f3e0-43a3-a779-1113d86cc5ee

spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data
    namespace: teamspeak
  csi:
    driver: csi.san.synology.com
    fsType: btrfs
    volumeAttributes:
      baseDir: ""
      dsm: 172.16.2.17
      formatOptions: --nodiscard
      mountPermissions: ""
      protocol: iscsi
      source: ""
      storage.kubernetes.io/csiProvisionerIdentity: 1740323674035-8081-csi.san.synology.com
    volumeHandle: 2c6a17f9-f7f9-4b7e-85e5-a4d87f78bad5
  persistentVolumeReclaimPolicy: Delete
  storageClassName: beryllium-iscsi
  volumeMode: Filesystem
