apiVersion: v1
kind: PersistentVolume

metadata:
  name: pvc-77f97c58-db4d-4205-80a0-dbdc42c2db66

spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: teamspeak-data
    namespace: teamspeak
  csi:
    driver: csi.san.synology.com
    volumeAttributes:
      dsm: 172.16.2.17
      location: /volume1
      mountPermissions: ""
      protocol: nfs
      source: //172.16.2.17/k8s-csi-pvc-77f97c58-db4d-4205-8
    volumeHandle: b88af8c9-2633-4a97-bab3-546a7341d50f
  mountOptions:
    - nfsvers=4.1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: beryllium-nfs
  volumeMode: Filesystem
