apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: data

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: beryllium-iscsi
  volumeMode: Filesystem
  volumeName: pvc-2d76d711-f3e0-43a3-a779-1113d86cc5ee
