apiVersion: v1
kind: Service

metadata:
  name: teamspeak-lb
  labels:
    chlorinate.rokoucha.com/lb: public
  annotations:
    lbipam.cilium.io/sharing-key: public-dmz
    lbipam.cilium.io/sharing-cross-namespace: "*"

spec:
  selector:
    app: teamspeak
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: RequireDualStack
  externalTrafficPolicy: Cluster
  ports:
    - name: voice
      port: 9987
      targetPort: 9987
      protocol: UDP
    - name: serverquery
      port: 10011
      targetPort: 10011
      protocol: TCP
    - name: filetransfer
      port: 30033
      targetPort: 30033
      protocol: TCP
