apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: teamspeak-data
  namespace: teamspeak

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: beryllium-nfs
  volumeMode: Filesystem
  volumeName: pvc-77f97c58-db4d-4205-80a0-dbdc42c2db66
