apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement

metadata:
  name: public-test-lb-advertisement
  labels:
    advertise: "public-test"

spec:
  advertisements:
    - advertisementType: Service
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchExpressions:
          - key: chlorinate.rokoucha.com/lb
            operator: In
            values:
              - public-test
