apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig

metadata:
  name: materia-bgp
  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  nodeSelector:
    matchLabels:
      chlorinate.rokoucha.com/bgp: srv-lan
  bgpInstances:
    - name: materia-instance
      localASN: 64513
      peers:
        - name: router-v4
          peerASN: 64512
          peerAddress: 172.16.2.1
          peerConfigRef:
            name: router-peer-config-v4
        - name: router-v6
          peerASN: 64512
          peerAddress: 240b:10:3f6d:1402:2e0:b4ff:fe6c:8087
          peerConfigRef:
            name: router-peer-config-v6
