apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig

metadata:
  name: materia-bgp
  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  nodeSelector:
    matchLabels:
      chlorinate.rokoucha.com/bgp: srv-lan
  bgpInstances:
    - name: materia-instance
      localASN: 64513
      peers:
        - name: router
          peerASN: 64512
          peerAddress: 172.16.2.1
          peerConfigRef:
            name: router-peer-config
