apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig

metadata:
  name: router-peer-config

spec:
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "public-test"
    - afi: ipv6
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "public-test"
