apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig

metadata:
  name: router-peer-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "public-test"
    - afi: ipv6
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "public-test"
