apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool

metadata:
  name: materia-public-ipv6
  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  blocks:
    - cidr: 240b:10:3f6d:1403::10/128
  serviceSelector:
    matchLabels:
      chlorinate.rokoucha.com/lb: public
