apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool

metadata:
  name: materia-public-ipv6

spec:
  blocks:
    - cidr: 2404:9200:225:103::/112
  serviceSelector:
    matchLabels:
      chlorinate.rokoucha.com/lb: public-test
