apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool

metadata:
  name: materia-public-ipv4
  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  allowFirstLastIPs: "Yes"
  blocks:
    - cidr: 172.16.2.30/32
  serviceSelector:
    matchLabels:
      chlorinate.rokoucha.com/lb: public
