apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mirakurun
spec:
  podSelector:
    matchLabels:
      app: mirakurun
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: haproxy-controller
          podSelector:
            matchLabels:
              app.kubernetes.io/name: kubernetes-ingress
              app.kubernetes.io/instance: haproxy-ingress
      ports:
        - port: 40772
          protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: mirakurun-egress
  namespace: mirakurun
spec:
  endpointSelector:
    matchLabels:
      k8s:app: mirakurun
  enableDefaultDeny:
    ingress: false
    egress: false
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s:k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: TCP
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: '*'
    - toFQDNs:
        - matchName: mirakurun.ggrel.net
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: haproxy-controller
            k8s:app.kubernetes.io/name: kubernetes-ingress
            k8s:app.kubernetes.io/instance: haproxy-ingress
      toPorts:
        - ports:
            - port: "8443"
              protocol: TCP
