apiVersion: v1
kind: Service

metadata:
  name: service
  annotations:
    backend.materia.ggrel.net/forward-auth: "true"

spec:
  selector:
    app: mirakurun
  type: ClusterIP
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: RequireDualStack
  ports:
    - name: mirakurun
      port: 40772
      targetPort: mirakurun
