apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx

resources:
  - ./resources/deployment.yaml
  - ./resources/ggrel-net-tls.yaml
  - ./resources/ingress.yaml
  - ./resources/namespace.yaml
  - ./resources/noa-pp-ua-tls.yaml
  - ./resources/rokoucha-net-tls.yaml
  - ./resources/sayn-wittgenste-in-tls.yaml
  - ./resources/service.yaml

configMapGenerator:
  - name: config
    files:
      - ./config/nginx.conf
