apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: otel-external

resources:
  - ./resources/namespace.yaml
  - ./resources/otelcol-external-ingress.yaml
  - ./resources/otelcol-external-tls.yaml
  - ./resources/otelcol-external-token.yaml
  - ./resources/otelcol-external.yaml
