apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: data

spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: beryllium-iscsi
  volumeMode: Filesystem
  volumeName: pvc-96cf017b-18b6-4e2c-a62f-a700d5e85736
